/* Print edition 22. Answers are independently derived by creepy_mechanics.py. */
function registerThreadGame(games) {
 const p=[
 {page:2,answer:'NACHT',hint:'Die Stimme kann Texte imitieren, aber nicht jede alte Prüfsumme. Trennt zuerst die echten Datensätze von den falschen.',hint2:'Zählt alle Einsen eines Fünferblocks einschließlich Prüfbit. Behaltet nur gerade Anzahlen. Sortiert danach Datum und Uhrzeit; lest die Satzanfänge.',taunt:'Das Forum zählt bis zwei. Ihr schafft das bestimmt auch ohne Moderation.',praise:'Die fremden Beiträge sind aussortiert.',
 beat:'Fünf Beiträge gehören derselben Nacht. Dazwischen stehen drei Kopien, die sich fast überzeugend anhören. Im letzten echten Beitrag steckt ein Anhang: fünf kurze Aufnahmen. Ihre Zeitstempel wurden entfernt. Jemand wollte verhindern, dass ihr merkt, wer zuerst gesprochen hat. Eine unbekannte Nutzerin schreibt: „Wenn ihr meine Reihenfolge findet, hört ihr mich vielleicht wieder.“',
 solutionSteps:['Gültige Blöcke: 10010, 10100, 11110, 11000, 01100. Die anderen haben eine ungerade Anzahl Einsen.','Zeitfolge: 17.11. 23:54, 23:58; dann 18.11. 00:01, 00:04, 00:07. Die Anfangsbuchstaben der zugehörigen Sätze ergeben N A C H T.']},
 {page:6,answer:'KABEL',hint:'Führt zwei Reihen parallel: Personen und Geräte. Direkte Nachbarschaft bedeutet genau einen Platz Abstand.',hint2:'Telefon ist auf Platz 5; Iris deshalb auf 4. Ihr Monitor ist ebenfalls dort. Kombiniert Veras Position zwischen Falk und Iris mit Mira/Band und dem Abstand zum Funkgerät.',taunt:'Fünf Stimmen und nur eine gemeinsame Reihenfolge. Immerhin mehr Ordnung als im Kommentarbereich.',praise:'Die Aufnahmen haben wieder eine Reihenfolge.',
 beat:'Als die fünfte Aufnahme einrastet, hört ihr zum ersten Mal ein Geräusch, das nicht vom Gebäude stammt: einen kurzen Atemzug vor dem Mikrofon. Nicht bedrohlich, sondern erschöpft. Die Nutzerin war beim Abschalten des Archivs noch im Raum. Das Forum speichert ihre Antworten seitdem immer wieder neu. Der Logikspeicher enthält den Schlüssel, mit dem man die älteren Fassungen öffnen kann.',
 solutionSteps:['Personen von früh nach spät: MIRA, FALK, VERA, IRIS, NILS. Geräte: BAND, KAMERA, FUNK, MONITOR, TELEFON. Alle zehn Aussagen passen nur zu dieser Belegung.','Kennzeichen in dieser Reihenfolge: K, A, B, E, L. Eingabe KABEL.']},
 {page:3,answer:'4173',inputMode:'numeric',hint:'Nicht jede leere Zelle ist sofort entscheidbar. Vergleicht auch, wo eine Ziffer innerhalb eines Blocks überhaupt noch stehen darf.',hint2:'Nutzt Schnittmengen von Zeile, Spalte und Block. Eine Ziffer, die in einem Block nur noch in einer Zeile möglich ist, kann außerhalb des Blocks in dieser Zeile gestrichen werden. Erst am Ende A–D auslesen.',taunt:'Der Speicher ist beschädigt. Eure Notizen müssen es nicht auch noch sein.',praise:'Der Schlüssel ist vollständig.',
 beat:'Der Speicher öffnet keine Tür. Stattdessen zeigt er ein winziges Bild, das aus Unterbrechungen besteht. Die Nutzerin erklärt: „Es sieht nur dann zurück, wenn die Lücken falsch sind.“ Ihr entscheidet euch, nicht darüber nachzudenken, was „es“ bedeutet. Noch nicht. Erst muss das Bild korrekt rekonstruiert werden. Bewahrt den vierstelligen Schlüssel auf; die Archivsoftware wird ihn erneut verlangen.',
 solutionSteps:['Das Sudoku hat genau eine vollständige Lösung. Die markierten Felder ergeben A=4, B=1, C=7, D=3.','Eingabe 4173. Das vollständige Raster steht zusätzlich im getrennten Spielleiter-Prüfbericht.']},
 {page:8,answer:'2212',inputMode:'numeric',hint:'Die Randzahlen bezeichnen Gruppen, nicht einzelne Koordinaten. Die kleinen Kreuze sind sicher weiße Felder.',hint2:'Beginnt mit Zeilen oder Spalten, deren Gruppen samt Pflichtabständen viel Platz brauchen. Markiert Überschneidungen aller möglichen Lagen. Gezählt werden anschließend nur die je vier Felder innerhalb der kleinen Rahmen A–D, nicht ganze Zeilen.',taunt:'Das Rauschen hat eine Struktur. Das Gekritzel neben eurem Raster hoffentlich auch.',praise:'Das Rauschen gibt seinen Aufbau preis.',
 beat:'Im Muster erscheint ein geschlossenes Auge. Ihr habt es nicht geöffnet, sondern ihm seine Form zurückgegeben. Auf der Rückseite des Bildes liegt ein Netzplan des Gebäudes. Die Nutzerin meldet eine Sperre, die auf keiner gedruckten Karte verzeichnet ist. Das Archiv wächst nicht wirklich. Es kopiert bloß die falschen Verbindungen. Ein unnötiger Umweg gibt dem Echo Zeit, eure Spur einzuholen.',
 solutionSteps:['Das Nonogramm ist mit den gedruckten Vorgaben eindeutig. Schwarze Felder pro Zeile: 4,2,4,4,4,4,4,4,2,4. Für die Antwort aber nur die vier kleinen Rahmen zählen.','A (Zeilen 1–2, Spalten 5–6): 2; B (Zeilen 3–4, Spalten 1–2): 2; C (Zeilen 6–7, Spalten 6–7): 1; D (Zeilen 9–10, Spalten 3–4): 2. Eingabe 2212.']},
 {page:4,answer:'AEFBCDHL',relatedPages:[6],transmission:'LIVE-SPERREN // Knoten G ist unpassierbar. Besucht zuerst E, später H, bevor ihr L erreicht. Minimiert die Summe der Verbindungskosten. Kein Knoten darf zweimal vorkommen. Die Durchsage wurde mit eurem Kennwort aus R2 authentifiziert.',hint:'Die kürzeste Linie auf dem Papier ist nicht automatisch der günstigste gültige Weg. Sperre und Pflichtstationen sind genauso wichtig wie die Kosten.',hint2:'Von A muss E vor H besucht werden. Streicht G vollständig. Vergleicht ab E die Wege, die ohne Wiederholung über H nach L führen. Addiert jede benutzte Verbindung genau einmal.',taunt:'Der Flur ist endlos. Euer zulässiger Weg zum Glück nicht.',praise:'Ihr erreicht den stillen Teil des Archivs.',
 beat:'Der letzte Gang endet vor einer Glasscheibe. Dahinter steht derselbe Schreibtisch wie auf dem Titelblatt, nur ohne Staub. Auf dem Bildschirm erscheint eine Nachricht in unlesbarer Reihenfolge. Die Nutzerin tippt langsamer: „Es hat zwei Schlösser darübergelegt. Nicht weil ich gefährlich bin. Weil ich weiß, wie man aufhört.“ Ihr habt beide Schlüssel schon gefunden. Jetzt müssen sie in der richtigen Reihenfolge benutzt werden.',
 solutionSteps:['Der eindeutig günstigste zulässige Weg lautet A–E–F–B–C–D–H–L. Seine Kosten betragen zusammen 45. G wird nicht betreten, E liegt vor H, kein Knoten wiederholt sich.','Eingabe AEFBCDHL. Die Kosten sind nur eine Kontrolle, nicht die einzugebende Antwort.']},
 {page:10,answer:'KEINERISTALLEIN',relatedPages:[2,3],hint:'Der zuletzt ausgeführte Verschlüsselungsschritt muss zuerst rückgängig gemacht werden. Der Block enthält gleich lange Spalten.',hint2:'Teilt den 16er-Block in vier Gruppen à vier Zeichen. Der Schlüssel 4173 ordnet die Spalten: B, D, A, C. Setzt sie an ihre Plätze zurück, lest zeilenweise und zieht dann die wiederholten Werte des R1-Wortes ab.',taunt:'Zwei Schlösser, zwei Schlüssel. Nur die Reihenfolge ist offenbar noch im Urlaub.',praise:'Die Nachricht ist nicht mehr allein im Speicher.',
 beat:'Die Botschaft klingt tröstlich. Dann wird euch klar, dass sie auch eine Warnung sein kann. Neben dem Schreibtisch hängen zwei Kontaktblätter. Das Echo hat kleine Zustände geändert, um so zu tun, als wäre die Anlage unverändert. Die Nutzerin bittet euch, nicht die Zeichnungen zu deuten: „Es lebt von dem, was ihr hineinsehen wollt. Vergleicht nur das, was wirklich da ist.“',
 solutionSteps:['Spaltengruppen: EETP | UULK | XXAG | KIYG. In Reihenfolge B,D,A,C einsetzen; zeilenweise ergibt das XEKU XEIU ATYL GPGK.','Mit NACHTNACHTNACHTN die Schlüsselwerte abziehen (A=0, modulo 26). Es entsteht KEINERISTALLEINX. Nur das letzte X entfernen: KEINERISTALLEIN.']},
 {page:5,answer:'120112',inputMode:'numeric',relatedPages:[11],hint:'Vergleicht ausschließlich die gerahmten Felder. Ein geänderter Punktzustand reicht, damit ein Feld als verändert zählt.',hint2:'Geht zeilenweise vor und hakt jede der sechs Spalten ab. Tragt pro Zeile eine Anzahl ein, auch bei null Änderungen. Leere und gefüllte Punkte sind unterschiedliche Zustände.',taunt:'Die Bilder unterscheiden sich. Eure Methode „ungefähr gleich“ hilft hier leider nicht.',praise:'Alle manipulierten Zustände sind protokolliert.',
 beat:'Sieben veränderte Felder. Keine davon war ein Druckfehler. Die Anlage hat sieben kleine Lügen gebraucht, um ihre Kopie unauffällig wirken zu lassen. Unter dem zweiten Kontaktblatt steht der Schaltplan ihrer Rückkopplung. Jeder Kreis muss genau einmal verstummen. Zu viele Abschaltungen würden nicht nur das Echo treffen, sondern auch die Stimme, die euch bisher geholfen hat.',
 solutionSteps:['Veränderte Felder: E1, B2, F2, C4, A5, D6, F6. Insgesamt sieben Felder.','Je Zeile 1 bis 6: 1,2,0,1,1,2. Eingabe 120112. Die übrigen Bildbereiche sind keine Rätselmerkmale.']},
 {page:11,answer:'EFGH',hint:'Ein Kreis darf nicht doppelt vorkommen. Streicht für jede gewählte Zweiergruppe alle Relais, die einen dieser Kreise erneut schalten würden.',hint2:'Ihr benötigt genau vier Relais. Sucht zunächst vollständige Belegungen aller acht Kreise, vergleicht erst dann deren Gesamtkosten. Die einzeln billigsten Relais sind nicht automatisch miteinander verträglich.',taunt:'Einmal abschalten reicht. Das Echo freut sich allerdings über großzügige Doppelarbeit.',praise:'Die Rückkopplung ist unterbrochen.',
 beat:'Vier Relais fallen ab. Im Raum wird es still genug, um Papier rascheln zu hören. Der letzte Moderator hat seine Antwort in sechs Stücke gerissen. Nicht um sie zu vernichten, sondern um sie dem automatischen Leser zu entziehen. Die Stücke lagen die ganze Zeit offen im Archiv. Eine Maschine sah sechs Dateien. Ihr könnt daraus wieder einen Satzanfang machen.',
 solutionSteps:['E deckt 1/3, F deckt 2/4, G deckt 5/7, H deckt 6/8. Jeder Kreis ist genau einmal abgedeckt. Gesamtkosten 4+7+3+5=19.','Alle vollständigen Belegungen wurden verglichen; die nächste kostet 20. Die günstigste ist eindeutig. Alphabetisch eingeben: EFGH.']},
 {page:7,answer:'CHORUS',hint:'Die Rechnung rechts liefert die Anschlussnummer, nicht den nächsten Buchstaben. Die Karten bleiben alle aufrecht.',hint2:'Sucht zuerst den Eingang 17. Rechnet den rechten Ausgang aus und sucht genau diesen Eingang auf einer unbenutzten Karte. Kontrolliert, dass ihr mit allen sechs Karten bei 99 endet.',taunt:'Der Schredder hat die schwierige Hälfte übernommen. Ihr seid jetzt mit der anderen dran.',praise:'Der zerrissene Datensatz ist wieder verbunden.',
 beat:'CHORUS war kein Benutzername. Es war der Name des Programms, das Antworten aus alten Beiträgen zusammensetzte. Es lernte nie, wann eine Unterhaltung vorbei war. Sechs Stimmen behaupten nun, den stillen Server zu kennen. Drei erzählen die Wahrheit. Die anderen wiederholen Sätze, die irgendwann einmal richtig gewesen sind. Ihr müsst nicht entscheiden, wem ihr vertraut – nur, welche Aussagen zusammenpassen.',
 solutionSteps:['Fragmentfolge: 4,1,6,2,5,3. Die Anschlusswerte sind 17→42→31→68→25→54→99.','Große Buchstaben entlang der Kette: C H O R U S. Eingabe CHORUS.']},
 {page:12,answer:'KELLER',hint:'Nehmt einen Zugang an und bewertet alle sechs Aussagen für genau diesen Fall. Eine Aussage wird nicht wahr, nur weil die Stimme überzeugend klingt.',hint2:'Legt eine Tabelle mit den sechs möglichen Zugängen an. Zählt pro Zugang die wahren Aussagen und prüft zusätzlich, ob Stimme 1 und 4 übereinstimmen.',taunt:'Drei Lügen und drei Wahrheiten. Fast ein gewöhnlicher Forenabend.',praise:'Der echte Zugang ist gefunden.',
 beat:'Am Kellerzugang fehlt das Namensschild. Stattdessen klebt dort ein Depotvermerk aus der Zeit vor dem Forum. Die unbekannte Nutzerin schickt nur noch ein Symbol: einen umgedrehten Pfeil. „Ihr habt es am Anfang schon in der Hand gehabt.“ Sie meint nicht den ersten Beitrag. Sie meint die Akte selbst. Das Archiv hat seinen Kontrollschlüssel dort versteckt, wo niemand eine Aufgabe erwartet.',
 solutionSteps:['Für KELLER sind Aussagen 1,4,5 wahr und 2,3,6 falsch. Genau drei sind wahr; 1 und 4 stimmen überein.','Die anderen Zugänge erfüllen die Wahrheitszahl nicht. Eingabe KELLER.']},
 {page:1,answer:'NULL',hint:'Untersucht das Titelblatt, nicht die erste Rätselseite. Ein kleiner Depotvermerk ist absichtlich anders ausgerichtet.',hint2:'Dreht das ganze Blatt um 180 Grad. Die vier Ziffern des Depotvermerks wählen jeweils einen Buchstaben aus dem Wort derselben Position. Zählt innerhalb des Wortes ab 1.',taunt:'Das Titelblatt war nicht nur Dekoration. Es nimmt eure Überraschung persönlich.',praise:'Der Kontrollschlüssel ist gesichert.',
 beat:'Vier Zeichen. Eine ausdrückliche Abwesenheit. CHORUS konnte mit jedem Wort umgehen, solange es eine Fortsetzung versprach. Diesen Schlüssel hat die Archivarin selbst angebracht. Dahinter liegt keine weitere Antwort, sondern eine Drehmaske: ein Lesefenster, das immer nur einen Teil des Textes freigibt. Zum ersten Mal bestimmt ihr, was die Maschine überhaupt sehen darf.',
 solutionSteps:['Depotindex 3142 auf dem umgedrehten Titelblatt. Wörter: TANNE, UFER, STILLE, BLATT.','3. Buchstabe aus TANNE=N; 1. aus UFER=U; 4. aus STILLE=L; 2. aus BLATT=L. Eingabe NULL.']},
 {page:13,answer:'VERLASSTDENKANAL',relatedPages:[9],hint:'Die Maske dreht sich, das Lesefeld bleibt liegen. Nach jeder Drehung beginnt die Leserichtung wieder oben links.',hint2:'Lest pro Stellung genau vier Fenster zeilenweise. Es gibt vier Stellungen insgesamt: Start, 90°, 180°, 270°. Alle 16 Felder werden genau einmal sichtbar. Alternativ funktioniert die gedruckte Koordinatenregel ohne Schere.',taunt:'Vier Fenster, vier Stellungen. Das ist noch kein Anlass, das Handy mitzudrehen.',praise:'Die versiegelte Anweisung ist gelesen.',
 beat:'Die Anweisung klingt wie Flucht. Aber einfach zu verschwinden würde die Archivarin zurücklassen. Sie erklärt, was fehlt: Das Programm hat ihren Namen durch eine Prüfsumme ersetzt. Ein Byte ist noch da, verteilt über acht Aussagen. Wenn ihr es rekonstruiert, kann sie beweisen, dass sie eine Person ist und keine weitere automatisch erzeugte Antwort.',
 solutionSteps:['Startfenster: (1,1),(1,2),(1,3),(2,2). Pro Drehung (Zeile,Spalte)→(Spalte,5−Zeile); danach wieder zeilenweise sortieren.','Die vier Blöcke lauten VERL | ASST | DENK | ANAL. Alle 16 Buchstaben zusammen: VERLASSTDENKANAL.']},
 {page:9,answer:'165',inputMode:'numeric',hint:'Jede Zeile ist eine Aussage über gerade oder ungerade Summen. Die Bits haben nur zwei mögliche Werte; dieselben Bits können in mehreren Zeilen vorkommen.',hint2:'Notiert jede Zeile als Summe ihrer markierten Bits modulo 2. Beim Kombinieren zweier Zeilen fallen doppelt vorkommende Bits weg. So lassen sich einzelne Bits isolieren. Erst zum Schluss mit 128,64,…,1 in eine Dezimalzahl umrechnen.',taunt:'Acht kleine Schalter. Eine erstaunlich große Menge Stirnrunzeln.',praise:'Das fehlende Byte ist rekonstruiert.',
 beat:'Die Zahl ist kein Name. Aber sie beschreibt, welche Hälfte von acht erhaltenen Zeichenpaaren wirklich zur Archivarin gehört. Die andere Hälfte stammt aus den automatischen Antworten. Die Nutzerin wartet, während ihr die Zeichen auswählt. Zum ersten Mal wird kein neuer Beitrag erzeugt. Das System hat gelernt, dass auf eine Frage nicht sofort die nächste Antwort folgen muss.',
 solutionSteps:['Die acht Paritätsbedingungen haben genau eine Belegung: B1…B8 = 1,0,1,0,0,1,0,1. Jede gedruckte Restspalte wird damit erfüllt.','Aktive Gewichte: 128+32+4+1=165. Eingabe 165. Die Bits aufbewahren.']},
 {page:14,answer:'NORA',relatedPages:[9,1],hint:'Nutzt den rekonstruierten Byte erneut. Die Zeichenpaare sind nicht frei wählbar; jedes hat sein eigenes Bit.',hint2:'Schreibt die acht Bits von höchstem zu niedrigstem Gewicht. 0 wählt links, 1 rechts. Kontrolliert die letzten vier gewählten Zeichen mit dem Titelblatt-Schlüssel, bevor ihr den Namen eingebt.',taunt:'Bitte keinen Namen raten. Das hat das Forum jahrelang für euch erledigt.',praise:'Die Archivarin hat ihren Namen zurück.',
 beat:'„Nora“, schreibt sie. Darunter erscheint ein Zeitstempel von heute. Keine Kopie mehr. Nora hat vor Jahren versucht, CHORUS abzuschalten, bevor es die letzten echten Beiträge überschreibt. Sie hat sich nicht im Gebäude verirrt, sondern in dessen Antworten. Jetzt fehlt nur die letzte Verbindung. Das Schloss akzeptiert keinen Namen und keine Bitte: Es verlangt einen fünfstelligen Code. Nora schickt euch die bisher fehlende Prüfzeile.',
 solutionSteps:['165 als acht Bits: 10100101. Die ausgewählten Buchstaben ergeben N O R A N U L L.','Die letzten vier Zeichen sind NULL, passend zu R11. Die ersten vier ergeben die bestätigte Identität. Eingabe NORA.']},
 {page:15,answer:'64027',inputMode:'numeric',transmission:'',hint:'FEST und VERSETZT sind getrennte Anzahlen. Zusammen verraten sie, wie viele Ziffern eines Versuchs überhaupt zum Code gehören.',hint2:'Bestimmt mögliche Mengen aus fünf verschiedenen Ziffern und streicht unpassende anhand aller Prüfzeilen einschließlich Noras Nachricht. Verteilt erst danach die verbleibenden Ziffern auf Positionen. Ein Kandidat muss jede Zeile exakt erfüllen.',taunt:'Das letzte Schloss freut sich über jedes „fast richtig“. Es sammelt diese Momente.',praise:'Die letzte Verbindung lässt sich lösen.',
 beat:'Das Schloss gibt nach. Nora schreibt keine neue Anweisung. Sie stellt eine Frage: „Wenn ich gehe, muss dann alles verschwinden, was ich hier festgehalten habe?“ Ihr seht den Unterschied zwischen ihrem Archiv und der Kopie zum ersten Mal klar. Erinnerungen dürfen bleiben. Nur die Maschine muss aufhören, so zu tun, als seien sie noch am Leben.',
 solutionSteps:['Vergleicht jeden Kandidaten mit sämtlichen gedruckten Prüfzeilen und der Zusatzzeile in der App. Ohne die App-Zeile bleiben mehrere Kandidaten übrig.','Genau ein fünfstelliger Code aus verschiedenen Ziffern 0–7 erfüllt alle Bewertungen: 64027. Eingabe 64027.']}
 ];
 p[2].solutionSteps.push(...threadSolutionDetails.sudoku.map((r,i)=>`Vollständige Sudoku-Zeile ${i+1}: ${r.join(' ')}`));
 p[3].solutionSteps.push(...threadSolutionDetails.nono.map((r,i)=>`Zeile ${i+1}, schwarze Spalten: ${[...r].flatMap((c,j)=>c==='1'?[j+1]:[]).join(', ')}.`));
 p.forEach((q,i)=>{q.no=i+1;q.viewerWarning=['Die Archivlupe zeigt das Blatt, nicht die Antwort. Wirklich öffnen?','Größere Zeichen sind erlaubt. Größere Ausreden leider nicht. Ansicht öffnen?','Das Archiv stellt scharf. Den Gedanken müsst ihr selbst fassen. Öffnen?'][i%3]});
 p[14].transmission=`NORA // Letzte Prüfzeile: Versuch ${threadFinalClue.guess}; FEST = ${threadFinalClue.fixed}; VERSETZT = ${threadFinalClue.moved}. Verwendet diese Zeile zusätzlich zu ALLEN Zeilen auf Seite 15. Keine Ziffer kommt im gesuchten Code doppelt vor.`;
 games.thread={name:'Der letzte Thread',menuLabel:'Creepypasta / Archiv 0317',description:'Ein geschlossenes Forum. Eine echte Stimme zwischen falschen Antworten. Beendet die Unterhaltung.',cover:'assets/thread/cover.jpg',printFile:'downloads/der-letzte-thread-druckbilder.zip?v=22',pageAssets:{folder:'assets/thread/seiten',prefix:'Der-letzte-Thread-Seite-'},meta:['15 Rätsel','Zeitbudget: 120–180 Min.','Sehr anspruchsvoll'],caseNumber:'0317–N',classification:'NICHT ANTWORTEN',theme:{mode:'creepypasta',accent:'#b55b65'},story:'Nur die App kennt die Reihenfolge. Sichert eure Ergebnisse – das Archiv braucht sie später erneut.',
 openingTitle:'NEUE ANTWORT / THREAD 0317',opening:[
 'Das Stadtarchiv schloss sein Internetforum vor sieben Jahren. Die letzte Nachricht bestand aus drei Wörtern: „Bitte nicht antworten.“ Heute Morgen lag ein Ausdruck davon in eurem Briefkasten. Darunter stand eine Antwort, datiert auf heute Nacht. Der Benutzername war unlesbar. Der Text nicht: „Ich glaube, ihr könnt mich noch hören.“',
 'Ihr recherchiert verschwundene Webseiten und alte Netzgeschichten. Normalerweise findet ihr defekte Links, halbe Bilder und Menschen, die sich falsch erinnern. Diese Akte ist anders. Ihre fünfzehn Seiten wurden sauber nummeriert, aber nicht in der Reihenfolge abgelegt, in der ihr sie brauchen werdet. Manche enthalten Material für zwei Aufgaben. Die App nennt immer die aktuelle Seite und die Rätselnummer.',
 'Eine Archivarin blieb während der letzten Abschaltung am Terminal. Nicht körperlich – der Raum wurde am nächsten Morgen leer gefunden. Doch im Forum erschienen weiter Antworten, die nur sie hätte schreiben können. Ein namenloses Programm sortierte längst selbst, was authentisch war. Es unterschied nicht mehr zwischen einer Person und der Kopie ihrer Wörter.',
 'Druckt alle fünfzehn Bilder einseitig auf A4 bei 100 %. Haltet Stifte, Notizpapier und eine Schere bereit. Eine Aufgabe verwendet eine Drehmaske; dafür gibt es auch eine gleichwertige Alternative ohne Schneiden. Keine Aufgabe benötigt unsichtbare Tinte, besondere Farben, Falten oder Ton. Wichtige Hinweise sind als klare Zeichen gedruckt, nicht zufällig in einer Illustration versteckt.',
 'Plant etwa 120–180 Minuten ein; das ist ein Entwicklungsziel und noch keine mit Testgruppen gemessene Spielzeit. Es gibt keinen Countdown und keine echten Warteaufgaben. Das Spiel ist fiktiv und ab 16 empfohlen: unheimliche Räume, digitale Identitätsverluste, keine Gewaltbilder und keine lauten Schreckmomente. Die Hilfe hat zwei Stufen und eine bestätigte Notfalllösung. Beginnt mit Seite 2, Rätsel 1.'
 ],puzzles:p,finale:{title:'Die Unterhaltung darf enden.',sound:true,soundProfile:'thread',stamp:'VERBINDUNG<br>GELÖST'}};
}

function showThreadFinale() {
 const box=$('stage');
 box.innerHTML=`<section class="finale thread-ending" aria-labelledby="finaleTitle"><p class="terminal-kicker">NORA / LETZTE VERBINDUNG</p><h2 id="finaleTitle">Lasst die Erinnerung bleiben.</h2><p>CHORUS wartet auf eine weitere Antwort. Nora wartet darauf, dass ihr keine mehr gebt.</p><div class="thread-connection"><span>ARCHIV</span><i aria-hidden="true"></i><span>CHORUS</span></div><p>Die echten Beiträge sind gesichert. Nur die automatische Wiederholung wird getrennt.</p><button id="threadDisconnect" type="button">Die letzte Verbindung trennen</button><button id="threadSound" type="button" class="secondary-action">Leisen Abschlussklang anhören</button></section>`;
 $('threadSound').onclick=()=>{armAudio();playFinalSound()};
 $('threadDisconnect').onclick=()=>{
  box.innerHTML=`<section class="finale thread-ending thread-released" aria-labelledby="finaleTitle"><div class="thread-dawn"><img src="assets/thread/dawn.jpg" alt="Das stille Archiv im Morgenlicht"><span aria-hidden="true"></span></div><p class="terminal-kicker">VERBINDUNG GETRENNT / ERINNERUNGEN BEWAHRT</p><h2 id="finaleTitle">Ein Morgen ohne Wiederholung.</h2><p class="thread-line">Die Antworten verstummen.</p><p class="thread-line">Im Archiv wird es hell.</p><p class="thread-line">Zum ersten Mal geht jemand durch die Tür hinaus.</p><button id="threadLetter" type="button">Noras zurückgelassenen Brief öffnen</button></section>`;
  $('threadLetter').onclick=()=>{
   box.innerHTML=`<section class="finale thread-ending" aria-labelledby="finaleTitle"><p class="terminal-kicker">PERSÖNLICH / KEINE AUTOMATISCHE ANTWORT</p><h2 id="finaleTitle">Für die Menschen am anderen Ende.</h2><div class="thread-letter"><p>Ich weiß nicht, wie lange ich hier war. Am Ende klangen selbst meine eigenen Sätze wie fremde Stimmen.</p><p>Ihr habt nicht einfach das richtige Passwort eingegeben. Ihr habt geprüft, widersprochen, neu angefangen und mich von den Kopien unterschieden. Ihr habt mir zugehört, ohne alles zu glauben. Genau das konnte CHORUS nie.</p><p>Bitte bewahrt die Akte auf. Nicht als Warnung. Als Beweis dafür, dass jemand zurückkommen kann, wenn andere lange genug nach ihm suchen.</p><p>Heute werde ich einen Kaffee bestellen und auf keine einzige Benachrichtigung reagieren.</p><p class="thread-signature">Nora</p></div><p class="thread-afterthought">Nachtrag: Im leeren Forum steht jetzt „0 Benutzer online“.<br>Darunter: „Danke fürs Warten.“<br>Der Beitrag hat keinen Antwortknopf.</p><a class="puzzle-download" href="downloads/noras-brief.html" download="Noras-Brief.html">Noras Brief als Erinnerung speichern ↓</a><button id="toMenu" type="button">Akte schließen</button></section>`;
   $('toMenu').onclick=()=>showMenu();box.scrollIntoView({block:'start',behavior:'smooth'});
  };box.scrollIntoView({block:'start',behavior:'smooth'});
 };box.scrollIntoView({block:'start',behavior:'smooth'});
}
