function registerMenuGame(games) {
  const steps=[
    {page:2,answer:'426539',hint:'Die Bonnummer ist kein Betrag. Rechnet aus Stückzahlen und Einzelpreisen den Sollbetrag jedes Bons aus.',taunt:'Die Kasse ist von 1978. Selbst sie schaut euch gerade skeptisch an.',
      praise:'Die manipulierten Bons sind aussortiert.',beat:'Lina antwortet zum ersten Mal: „Also habt ihr es gesehen.“ Die falschen Beträge sollten den Eindruck erwecken, das Restaurant sei längst unrentabel. Unter dem Kassenfach liegt der Dienstplan. Jemand hat die Namen entfernt, aber die Absprachen des Teams übersehen. Findet die Person, die heute den Koriander vorbereitet hat.',
      solutionSteps:['Sollbeträge von oben nach unten: 23,20,27,30,21,34 Euro. Falsch sind die Bons 42,65,39.','Bonnummern in dieser Reihenfolge zusammenhängen: 426539.']},
    {page:6,answer:'CEM',hint:'Setzt zuerst die mittlere Gewürzstation. Prüft, wo die beiden direkt benachbarten Gewürzpaare noch Platz haben. Erst danach die Namen zuordnen.',taunt:'Fünf Köche finden ihre Station. Nur eure Gedanken laufen noch durch den Spülbereich.',
      praise:'Das Küchenteam ist wieder vollständig.',beat:'Cem findet unter seinem Schneidebrett eine kleine Porzellantafel. Linas Großmutter Mira benutzte solche Tafeln, damit niemand ein Rezept allein beherrschen konnte. „Der nächste Schlüssel muss erarbeitet werden“, sagt Cem. Im Speisesaal werden inzwischen die Tischdecken abgezogen. Noch weiß niemand, dass ihr den Service retten wollt.',
      solutionSteps:['Gewürze von links nach rechts: ZIMT, PFEFFER, KORIANDER, SAFRAN, VANILLE.','Dora gehört zu Zimt, Ada zu Vanille. Emil bleibt Station 4. Bela steht vor Cem: Namenfolge DORA, BELA, CEM, EMIL, ADA. Bei Koriander steht CEM.']},
    {page:4,answer:'5273',inputMode:'numeric',hint:'Jede Ziffer darf pro Zeile, Spalte und Block nur einmal vorkommen. Notiert Kandidaten; die vier markierten Werte werden mehrfach gebraucht.',taunt:'Der Teller ist leer. Eure Kandidatenliste hoffentlich nicht.',
      praise:'Der Logikteller ist entschlüsselt.',beat:'Auf Linas Gerät erscheinen vier Schlüsselwerte. Sie schickt sie sofort an die übrigen Stationen. „Bitte nicht wegwerfen. Mira hat nie nur eine Tür mit einem Schlüssel geöffnet.“ Im Vorratsraum stehen drei unbeschriftete Probenschalen. Die Waagen funktionieren – ihre Etiketten fehlen. Ohne die ursprünglichen Mengen kann die Küche nicht weitermachen.',
      solutionSteps:['Das 9×9-Sudoku besitzt genau eine Lösung. Alle markierten Felder sind zu Beginn leer.','Auslese A=5, B=2, C=7, D=3. Eingabe 5273. Die Werte für den Servierweg und die Archivchiffre aufbewahren.']},
    {page:3,answer:'352015',inputMode:'numeric',hint:'Drückt aus der ersten Gleichung K mit M aus. Die zweite liefert A mit M. Setzt beides in die dritte Gleichung ein.',taunt:'Der Teig geht auf. Eure Rechnung braucht offenbar noch etwas Hefe.',
      praise:'Die Grundmischung stimmt wieder.',beat:'Die Mengen passen zu Miras alter Tarte. Cem erkennt den Duft, noch bevor irgendjemand den Ofen einschaltet. Auf dem Rezeptumschlag ist kein Name vermerkt, sondern ein kleines verschwommenes Geschirrbild. Lina erinnert sich: Ihre Großmutter versteckte wichtige Notizen zwischen den scheinbar unwichtigen Dingen. Was auf den Teller gehört, muss erst sichtbar werden.',
      solutionSteps:['K=55−M und A=85−2M. In K+3A=65 eingesetzt: 55−M+255−6M=65, also M=35.','Dann K=20 und A=15. Eingabe in Reihenfolge M–K–A: 352015. Eine Mischung von 70 g reicht für zwei Portionen.']},
    {page:8,answer:'253',inputMode:'numeric',hint:'Zeilen- und Spaltenhinweise gelten gleichzeitig. Beginnt mit Gruppen, die wegen ihrer Länge bestimmte Felder sicher belegen. Das vorgegebene Feld gehört dazu.',taunt:'Ihr zeichnet gerade das erste Gericht, das auch der Teller nicht erkennt.',
      praise:'Das verborgene Geschirr ist sichtbar.',beat:'Unter der Zeichnung steht ein einziges Datum: der Abend, an dem Mira das Restaurant eröffnete. Damals kamen mehr Menschen als geplant, doch niemand wurde fortgeschickt. Heute fehlen euch nicht die Plätze, sondern die Zeit. Der Ofenplan muss so gelegt werden, dass Backen, Temperaturwechsel und Ruhezeiten zusammenpassen. Wartet nicht wirklich – plant auf dem Papier.',
      solutionSteps:['Die vollständigen schwarzen Felder je Zeile: 3,5 / 4 / 2,3,4,5,6 / 2,6,7 / 2,6,7 / 2,3,4,5,6 / 3,4,5.','Zeile 1 hat 2 schwarze Felder, Zeile 3 hat 5 und Zeile 7 hat 3. Eingabe 253; das vorgegebene schwarze Feld mitzählen.']},
    {page:5,answer:'1800',acceptedAnswers:['18:00'],inputMode:'numeric',hint:'Prüft nicht nur die Summe der Backzeiten. Ein Temperaturwechsel kostet Zeit; die letzte Tarte benötigt auch nach dem Backen noch Ruhe.',taunt:'Der Ofen kann warten. Zwölf hungrige Gäste eher nicht.',
      praise:'Der Service ist rechtzeitig machbar.',beat:'Lina streicht den geplanten Verkaufstermin aus ihrem Kalender. „Noch ist nichts verloren.“ Während Cem die Bleche vorbereitet, ruft Dora aus dem Flur: Der Käufer hat die Wegweiser vertauscht. Auf dem alten Grundriss findet ihr noch die richtigen Koordinaten. Lina sendet eine Anweisung, deren Schrittlängen nur euer Logikteller verrät.',
      solutionSteps:['Kürzeste Gesamtdauer: 120 Minuten. Beispiel: Brot 0–30, Gemüse 30–50, Temperaturwechsel 50–60, Tarte 60–100, Gebäck 100–115; Tarte ruht bis Minute 120. Brot ist längst ausgeruht.','Alle 24 Reihenfolgen wurden verglichen; keine ist früher vollständig fertig. Für 20:00 Uhr muss der erste Backvorgang spätestens um 18:00 beginnen. Eingabe 1800.']},
    {page:9,answer:'E9',relatedPages:[4],transmission:'LINA // Verwendet die Werte A, B, C und D aus dem Logikteller. Start ist F7. Geht A Felder nach Norden, B nach Osten, C nach Süden und D nach Westen. Die Kücheninsel darf nicht betreten werden. Meldet nur die Zielkoordinate.',
      hint:'Die Buchstaben A–D im Funkspruch sind Schlüssel aus dem Sudoku, keine Koordinatenspalten. Führt die vier Bewegungen nacheinander aus.',taunt:'Ihr habt euch zwischen Vorratsraum und Spüle verlaufen. Beeindruckend auf einem Blatt Papier.',
      praise:'Der richtige Zugang ist gefunden.',beat:'Hinter dem unscheinbaren Zugang steht Miras Gewürzregal. Die Etiketten sehen vertraut aus, ergeben aber keinen Sinn. Lina hält eine Dose gegen das Licht. „Die Namen der Gewürze sind echt. Die Nachricht dazwischen wurde verdreht.“ Ihr braucht jetzt die Reihenfolge der Stationen und einen Mengenwert aus der Grundmischung.',
      solutionSteps:['Schlüssel A,B,C,D = 5,2,7,3. Von F7 fünf Felder nach Norden: F2. Zwei nach Osten: H2.','Sieben nach Süden: H9. Drei nach Westen: E9. Die Kücheninsel wird auf keinem Schritt betreten.']},
    {page:7,answer:'BRUEHE',acceptedAnswers:['BRUHE'],relatedPages:[6,3],hint:'Ordnet zuerst die fünf Gläser nach den Gewürzen im Stationsplan. K ist der Grammwert für Kakao. Macht die Vorwärtsverschiebung rückgängig.',taunt:'Die Gewürze haben mehr Ordnung im Regal als ihr in euren Notizen.',
      praise:'Miras Nachricht ist wieder lesbar.',beat:'Zwischen den Dosen liegt das Rezept für eine einfache Brühe. Auf der Rückseite steht: „Das Kostbarste war nie die geheime Zutat.“ Daneben findet ihr eine zerrissene Banderole. Die Teile wirken unscheinbar, doch ihre Linie läuft über mehrere Schnittkanten hinweg. Lina legt die Schere bereit. Es ist Zeit, das Ganze wieder zusammenzusetzen.',
      solutionSteps:['Stationsreihenfolge: ZIMT, PFEFFER, KORIANDER, SAFRAN, VANILLE. Die Dosen ergeben V L OY B Y, zusammen VLOYBY.','K=20. Jeden Buchstaben 20 Stellen zurücksetzen: B R UE H E. Eingabe BRUEHE beziehungsweise BRÜHE.']},
    {page:10,answer:'TEILEN',hint:'Die Oberkanten bleiben auf gleicher Höhe. Vergleicht die Austrittshöhe einer Linie rechts mit der Eintrittshöhe am nächsten Teil links. Nicht drehen.',taunt:'Die Schere hat ihren Teil erledigt. Für euren ist sie nicht zuständig.',
      praise:'Die Banderole ist wieder vollständig.',beat:'TEILEN steht auf dem Band. Nicht als Anweisung für die Portionen, sondern für den Besitz des Restaurants. Mira wollte, dass es dem ganzen Team gehört. Doch bevor ihr das Archiv öffnen könnt, kommt eine neue Bestellung herein. Cem hebt eine leere Kakaodose. Erst müsst ihr nachrechnen, ob der Vorrat wirklich reicht.',
      solutionSteps:['Beim Teil mit START beginnen. Die Linie ohne Höhenversatz bis ENDE fortsetzen; alle Oberkanten bleiben bündig.','Die sechs Buchstaben ergeben T E I L E N. Die Teile werden weder gedreht noch übereinandergelegt.']},
    {page:3,answer:'KAKAO60',relatedPages:[3],transmission:'NACHBESTELLUNG // Bestellt sind 30 Portionen. Plant 20 % Reserve zusätzlich ein. Eine Grundmischung reicht für zwei Portionen. Nutzt die Grammwerte aus Rätsel 4 und den gedruckten Vorrat. Antwort: Name der fehlenden Zutat direkt gefolgt von der fehlenden Grammzahl.',
      hint:'Rechnet zuerst die Reserveportionen aus und dann die Anzahl Grundmischungen. Vergleicht für jede Zutat Bedarf und Vorrat getrennt.',taunt:'Aus leerem Kakao lässt sich vieles machen. Eine korrekte Bestellung wäre ein Anfang.',
      praise:'Der fehlende Vorrat ist unterwegs.',beat:'Cem schickt Bela zur Nachbarküche. Es sind nur wenige Schritte – das Team dort hilft ohne zu fragen. Zum ersten Mal wirkt der bevorstehende Abend nicht wie ein Abschied. Lina öffnet Miras Kassette. Darin liegt der verschlüsselte Zusatz zum Kaufvertrag. Die vier Sudokuwerte passen auch hier. Jetzt geht es nicht mehr um Zutaten, sondern um die Zukunft des Hauses.',
      solutionSteps:['30 Portionen plus 20 % Reserve sind 36 Portionen, also 18 Grundmischungen. Bedarf: Mehl 18×35=630 g, Kakao 18×20=360 g, Mandelmehl 18×15=270 g.','Vorrat: 700,300,290 g. Nur Kakao fehlt: 360−300=60 g. Eingabe KAKAO60.']},
    {page:11,answer:'GEMEINSAM',relatedPages:[4],hint:'Die Schlüsselwerte sortieren die Spalten, nicht die einzelnen Zeichen. Jede Spalte enthält genau drei Zeichen. Setzt die vier Gruppen an ihre ursprünglichen Plätze zurück.',taunt:'Das Archiv lässt euch gern noch einmal von oben nach unten lesen.',
      praise:'Der Zusatzvertrag ist entschlüsselt.',beat:'„GEMEINSAM“, liest Lina. Der Vertrag enthält Miras letzte Verfügung: Der Verkauf ist ungültig, sobald das Team den Service aus eigener Kraft fortführt. Der Käufer klappt seine Mappe zu. Doch die Gäste warten noch immer vor dem verschlossenen Speisesaal. Der letzte Einlasscode wurde über eure ganze Küche verteilt. Tragt die Ergebnisse zusammen – niemand hat alles allein gelöst.',
      solutionSteps:['A,B,C,D tragen die Schlüssel 5,2,7,3. Aufsteigende Reihenfolge: B,D,A,C. Die Chiffre in vier Dreiergruppen teilen: ENX | EAX | GIM | MSX.','Spalten einsetzen: A=GIM, B=ENX, C=MSX, D=EAX. Zeilenweise lesen: GEME / INSA / MXXX. Die letzten X entfernen → GEMEINSAM.']},
    {page:12,answer:'TISCH',relatedPages:[6,3,9,8,5],hint:'Jede Zeile fragt nach einem bereits erarbeiteten Ergebnis. Wählt erst den passenden Eintrag und dann seinen Buchstaben. Nicht die Ergebniswörter selbst aneinanderhängen.',taunt:'Der Tisch ist gedeckt. Nur eure gesammelten Ergebnisse sitzen noch nicht zusammen.',
      praise:'Der Speisesaal öffnet sich.',beat:'Die Tür schwingt auf. Drinnen wartet kein strenger Restaurantkritiker, sondern die gesamte Nachbarschaft. Jeder hat etwas mitgebracht: Brot, Blumen, einen zusätzlichen Stuhl. Mira hatte ihren letzten Abend nie als Abschied geplant. Lina dreht das Schild an der Tür um. Auf der Rückseite steht: „Heute ist der erste Abend.“',
      solutionSteps:['Korianderkoch CEM→T; fehlender Kakao 60→I; Servierziel E9→S; Nonogramm 253→C; Ofenstart 1800→H.','Buchstaben von oben nach unten: TISCH. Das ist das letzte Passwort.']}
  ];
  steps.forEach((p,i)=>{
    p.no=i+1;
    p.hintWarning='Die Küche gibt euch einen kleinen Hinweis, aber der Küchenchef wird sich einen Kommentar nicht verkneifen. Wirklich öffnen?';
    p.viewerWarning=['Die Küchenlupe ist poliert. Eure Ausrede „zu klein gedruckt“ danach leider auch.','Ein Blick ins Arbeitsblatt – ohne dass die Küche euch die Lösung vorsagt.','Das Rezeptarchiv öffnet nur das Blatt, nicht automatisch euren Gedankengang.','Bitte keine Soße auf dem Display. Die Großansicht wird jetzt serviert.'][i%4];
  });
  games.menue={name:'Das letzte Menü',menuLabel:'Kulinarische Rätselakte',description:'Ein letzter Service, manipulierte Bons und ein Rezept, das allen gehört.',
    cover:'assets/menue-cover.png',printFile:'downloads/das-letzte-menue-druckbilder.zip',pageAssets:{folder:'assets/menue/seiten',prefix:'Das-letzte-Menue-Seite-'},
    meta:['12 Rätsel','Ziel: 60–90 Min.','Anspruchsvoll'],caseNumber:'FG–1978',classification:'KÜCHENINTERN',theme:{accent:'#728456',mode:'kueche'},
    story:'Rettet den letzten Service im Fünften Gang. Bewahrt eure Ergebnisse auf: Mehrere Schlüssel werden später erneut gebraucht.',
    openingTitle:'LINA // DER LETZTE SERVICE',opening:[
      'In neunzig Minuten erwartet das Restaurant „Fünfter Gang“ seine letzten Gäste. Küchenchefin Lina wollte Miras berühmtes Familienmenü servieren. Doch die Rezepte fehlen, mehrere Bons wurden manipuliert und ein Käufer wartet bereits auf die Schlüssel.',
      'Ihr seid das Küchenteam. Eine alte Arbeitsmappe und Linas Nachrichten sind alles, was euch bleibt. Prüft, kombiniert und bewahrt eure Ergebnisse auf. Manche Zahlen werden später wieder gebraucht. Ihr müsst weder kochen noch etwas probieren.',
      'Druckt alle zwölf Seiten einseitig auf A4 aus. Legt Stifte und eine Schere bereit. Die Spielzeit von 60–90 Minuten ist ein Planungsziel, noch kein gemessener Wert. Es gibt keinen echten Countdown und keine Wartepflicht. Beginnt auf Seite 2 mit Rätsel 1.'
    ],puzzles:steps,finale:{kicker:'DER SERVICE BEGINNT',title:'Für alle ein Platz.',text:'Ihr habt nicht nur ein Menü gerettet. Der Fünfte Gang gehört jetzt seinem Team. Lina stellt einen zusätzlichen Teller auf den Tisch: euren. Willkommen am ersten Abend einer neuen Geschichte.',stamp:'GEMEINSAM<br>GERETTET',image:'assets/menue-finale.png',imageAlt:'Ein gedeckter Teller mit Kräutern: Für alle ein Platz',sound:true}}
}
